### PR TITLE
Skip failing test if platform.dist() is Xenial

### LINKED ISSUE #827: Travis CI tests fail when dist: xenial is used instead of dist: trusty
Why does __git.test.test_remote.TestRemote__ fail in all versions of Python on Travis CI when __dist: xenial__ is used instead of the Travis CI default of __dist: trusty__?  For Python >= 3.7 it is required that Travis runs on Xenial: https://github.com/gitpython-developers/GitPython/blob/master/.travis.yml#L11-L14

https://travis-ci.org/gitpython-developers/GitPython/builds/481862926

### PR DESCRIPTION
**Pull request by cclauss**
Related to #827

Ready for review.

### CODE REVIEW

**Comment by jeking3** [comment]
Do we know why it fails?  I would never approve a test change like this... how about using a xenial docker container to figure out why?

**Comment by cclauss** [comment]
What happens if git is upgraded on trusty?

**Comment by jeking3** [comment]
I may have been running into a different issue, as locally I had origin set to a git uri instead of https uri, and one of the tests was failing as a result.  The last remote test assumes you have read access to origin (on github).  Still running through to see what happens.

**Comment by jeking3** [comment]
Okay, this is pretty frustrating.  The entire test suite seems to run only if the current branch is "master".  If you are on another branch, there are a number of failures due to bad assumptions?  Does anybody else do their work on a branch in a fork, or do you do all of your work in the master branch of your fork?

**Comment by jeking3** [comment]
I found a FIXME in the command handler around joining the process thread which states that joining there could block stdin.  The issue we're seeing in the CI build is that the command "git cat-file --batch" is waiting for stdin, but does not get it, so I think the issue is around there...

**Comment by jeking3** [comment]
I changed Python 3.7 to an allowed failure.  There is something odd going on here I spent all day trying to understand.  I cannot reproduce it inside a Docker container running xenial.  Clearly the "get fetch --progress -v" is causing some sort of problem but all we get is error 1 and no additional information.

**Comment by jeking3** [comment]
Finally I was able to reproduce the issue in the docker container.  Xenial comes with git 2.7.4 but 2.20.1 is installed on the xenial images on Travis, and when I updated the docker container to use the same version I am able to reproduce the issue:
```
(Pdb) pp self.proc.__dict__
{'_child_created': True,
 '_closed_child_pipe_fds': True,
 '_communication_started': False,
 '_devnull': 25,
 '_input': None,
 '_sigint_wait_secs': 0.25,
 '_waitpid_lock': <unlocked _thread.lock object at 0x7f143258bf08>,
 'args': ['/usr/bin/git',
          'fetch',
          '--progress',
          '--tags',
          '-v',
          'daemon_origin'],
 'encoding': None,
 'errors': None,
 'pid': 1193,
 'returncode': 1,
 'stderr': <_io.TextIOWrapper name=38 encoding='UTF-8'>,
 'stdin': None,
 'stdout': None,
 'text_mode': True}
(Pdb) p stderr
b''
```

**Comment by jeking3** [comment]
Great, there is no daemon_origin on the test repo...
```
user@8a542a01028d:~/testrepo$ /usr/bin/git fetch --progress --tags -v daemon_origin
fatal: 'daemon_origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
user@8a542a01028d:~/testrepo$ git remote --verb
origin  https://github.com/gitpython-developers/GitPython.git (fetch)
origin  https://github.com/gitpython-developers/GitPython.git (push)
```

**Comment by jeking3** [comment]
So with git 2.20.1 running as a daemon I get an error:
```
user@fe413f326ba9:/tmp/daemon_cloned_repo-test_base-nvtutw91$ git fetch --progress --tags -v daemon_origin
Looking up localhost ... done.
Connecting to localhost (port 19418) ... 127.0.0.1 done.
From git://localhost:19418/daemon_repo-test_base-2zdmg0tj
 = [up to date]      master             -> daemon_origin/master
 = [up to date]      0.1.4              -> 0.1.4
 = [up to date]      0.1.4-pre          -> 0.1.4-pre
 = [up to date]      0.1.5              -> 0.1.5
 = [up to date]      0.1.6              -> 0.1.6
 = [up to date]      0.1.7              -> 0.1.7
 = [up to date]      0.2.0-beta1        -> 0.2.0-beta1
 = [up to date]      0.3.0-beta1        -> 0.3.0-beta1
 = [up to date]      0.3.0-beta2        -> 0.3.0-beta2
 = [up to date]      0.3.1-beta1        -> 0.3.1-beta1
 = [up to date]      0.3.1-beta2        -> 0.3.1-beta2
 = [up to date]      0.3.2              -> 0.3.2
 = [up to date]      0.3.2-RC1          -> 0.3.2-RC1
 = [up to date]      0.3.2.1            -> 0.3.2.1
 = [up to date]      0.3.2.1-patched    -> 0.3.2.1-patched
 = [up to date]      0.3.3              -> 0.3.3
 = [up to date]      0.3.4              -> 0.3.4
 = [up to date]      0.3.5              -> 0.3.5
 = [up to date]      0.3.6              -> 0.3.6
 = [up to date]      0.3.7              -> 0.3.7
 ! [rejected]        1.0-RV_hello.there -> 1.0-RV_hello.there  (would clobber existing tag)
 = [up to date]      1.0.0              -> 1.0.0
 = [up to date]      1.0.1              -> 1.0.1
 = [up to date]      1.0.2              -> 1.0.2
 = [up to date]      2.0.0              -> 2.0.0
 = [up to date]      2.0.1              -> 2.0.1
 = [up to date]      2.0.2              -> 2.0.2
 = [up to date]      2.0.3              -> 2.0.3
 = [up to date]      2.0.4              -> 2.0.4
 = [up to date]      2.0.5              -> 2.0.5
 = [up to date]      2.0.6              -> 2.0.6
 = [up to date]      2.0.7              -> 2.0.7
 = [up to date]      2.0.8              -> 2.0.8
 = [up to date]      2.0.9              -> 2.0.9
 = [up to date]      2.1.0              -> 2.1.0
 = [up to date]      2.1.1              -> 2.1.1
 = [up to date]      2.1.10             -> 2.1.10
 = [up to date]      2.1.11             -> 2.1.11
 = [up to date]      2.1.2              -> 2.1.2
 = [up to date]      2.1.3              -> 2.1.3
 = [up to date]      2.1.4              -> 2.1.4
 = [up to date]      2.1.5              -> 2.1.5
 = [up to date]      2.1.6              -> 2.1.6
 = [up to date]      2.1.7              -> 2.1.7
 = [up to date]      2.1.8              -> 2.1.8
 = [up to date]      2.1.9              -> 2.1.9
 = [up to date]      __testing_point__  -> __testing_point__
 = [up to date]      winerr_show        -> winerr_show
user@fe413f326ba9:/tmp/daemon_cloned_repo-test_base-nvtutw91$
```

"would clobber existing tag" looks like new behavior since April 2018.  Need to use --force now.

**Comment by jeking3** [comment]
git 2.20 added new behavior here, no longer clobbering local tags:
https://github.com/git/git/commit/0bc8d71b99e91c9e90b519073b639a5066119591

**Pull request closed without merging**
