### PR TITLE
NOT FOR MERGE: travis testing across older (Neuro)Debian/Ubuntu chroots

### PR DESCRIPTION
**Pull request by yarikoptic**
Intended to help testing across various Debian/Ubuntu releases in preparation for the release

References: 
https://github.com/gitpython-developers/GitPython/issues/259#issuecomment-75266316

### CODE REVIEW

**Comment by Byron** [comment]
Thanks for picking this up again. Clearly I do not understand the purpose of this PR to the extend necessary, and wonder if there is something I should do with it :).

**Comment by yarikoptic** [comment]
@Byron :  well -- the purpose was to enable testing of GitPython against older releases of Debian/Ubuntu, for which I somewhat care about ;)  Since it is not a complete replacement of the previous setup (atm doesn't test across various 2.x and 3.x versions) it should not just be accepted (obviously).  I guess you could just close it and I would simply enable travis for my fork, so whenever new release comes up, I could quickly merge master/push and verify that GitPython still works fine across releases.

**Comment by Byron** [comment]
I don't mind at all to host this PR for an indefinite time - be my guest :).
Maybe you can make clear, for others, that this PR is for testing against older releases of Debian/Ubuntu, in the headline and text.
I shall keep it assigned to each upcoming release, just to remind myself to check with you before making any release.

**Comment by yarikoptic** [comment]
done

**Comment by yarikoptic** [comment]
by any chance -- going to PyCon this week @byron?

**Pull request closed without merging**
