### PR TITLE
Drop python 3.4, prep for adding types

### PR DESCRIPTION
**Pull request by Yobmod**
- Drop python 3.4 in setup.py and tox.ini
-  Update .gitnignore
- Add mypy.ini
- Add git/py.typed file and to setup.py
- add test/testrunner.py as a hook for monkeytype
- Add git/types.py for type aliases and classes
- (Some commits just formatting. VSCode switched my flake8 off for mypy)

### CODE REVIEW

**Comment by Yobmod** [comment]
I've had to rename testrunner.py as it was interferring with the checks. Feel free to change to a better name!

**Comment by Byron** [comment]
Thanks a lot! Please let me know if this is a draft (and I will make it a draft PR) or when it's ready to be merged as foundation for types (I really don't know much anything about that and rely solely on your expertise, thanks in advance for bearing my ignorance 😅).

**Comment by Yobmod** [comment]
I think this is ready to merge as is.
It doesn't touch any of the existing code (except setup.py), but get it all ready for adding types, whichever route we end up going for that.

**Comment by Byron** [comment]
Thanks a lot, I am looking forward to seeing the first types :)!

**Pull request merged**
