### PR TITLE
use git rev-parse to look for config file

### PR DESCRIPTION
**Pull request by bdauvergne**
It fixes config file finding when in a separate worktree.

If fixes the issue with worktree reported in https://github.com/gitpython-developers/GitPython/issues/719#issuecomment-362232645

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot for the contribution - I would love to merge, but can't as long as there is test breakage. Maybe it's an easy fix.

**Comment by bdauvergne** [comment]
I tried a work-around but i'm not sure of it, there is some circular dependency between the search got the .git directory in Repo and the initialization of the self.git command wrapper (the git command should be able to find the .git itself, but the late initialization has maybe some use).

**Comment by bdauvergne** [comment]
And it works (I don't know the problem with appveyor, I do not think it's related to my patch).

**Comment by Byron** [comment]
Thanks so much! I am glad you could find the time.
In the next days, GitPython 3 will be released and include the fix.

**Pull request merged**
