### PR TITLE
chore: Enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine,
CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a lot! Can you make it so it only runs once all tests have passed?

**Comment by naveensrinivasan** [comment]
> Thanks a lot!
> 
> Can you make it so it only runs once all tests have passed? And could you exclude the tests from being checked as well?

I can ignore the tests folder in this PR.

**Comment by Byron** [comment]
Thanks! Can you also make it so it only runs once all tests have passed?

**Comment by naveensrinivasan** [comment]
> Thanks! Can you also make it so it only runs once all tests have passed?

I can do that in the next PR.

**Review by Byron — CHANGES_REQUESTED** [review]
Alright, I will be waiting for exclusion of tests in this PR, so the dependency adjustment can be happening in the next one (even though I think it could happen in this one as well, but that might be a misconception).

**Comment by naveensrinivasan** [comment]
I am going to close this for now. I can probably pick it up later. Thanks

**Pull request closed without merging**
