### PR TITLE
Fix Repo.__repr__ when subclassed

### PR DESCRIPTION
**Pull request by yaccz**

### CODE REVIEW

**Comment by Byron** [comment]
Thanks for your contribution! It looks like travis failed, could you have a look?
Usually I would link the exact line of failure here, but it seems I can't access travis-ci right now.
My guess is that `git_dir` can't always be used safely.

**Comment by yaccz** [comment]
@Byron fixed.

**Comment by yaccz** [comment]
I do not know why AppVeyor is failing. It does not seem related to my changes.

**Comment by Byron** [comment]
Thanks a lot, and sorry for the late reply. Unfortunately the release train just left the station, which means this fix will land in 3.0.8.

**Pull request merged**
