### PR TITLE
Fix dynamically-set __all__ variable

### PR DESCRIPTION
**Pull request by DeflateAwning**
Fixes issue #1656 by statically setting the `__all__` variable.
Note that this could probably be done more preciely. The list was generated using the dynamic generation code currently there, printed, and then inserted back in.

### CODE REVIEW

**Review by Byron — CHANGES_REQUESTED** [review]
Thanks a lot!

It looks like the list is not complete though, is this intentional?

```python
Out[19]:
['Actor',
 'AmbiguousObjectName',
 'BadName',
 'BadObject',
 'BadObjectType',
 'BaseIndexEntry',
 'Blob',
 'BlobFilter',
 'BlockingLockFile',
 'CacheError',
 'CheckoutError',
 'CommandError',
 'Commit',
 'Diff',
 'DiffIndex',
 'Diffable',
 'FetchInfo',
 'Git',
 'GitCmdObjectDB',
 'GitCommandError',
 'GitCommandNotFound',
 'GitConfigParser',
 'GitDB',
 'GitError',
 'HEAD',
 'Head',
 'HookExecutionError',
 'IndexEntry',
 'IndexFile',
 'IndexObject',
 'InvalidDBRoot',
 'InvalidGitRepositoryError',
 'List',
 'LockFile',
 'NULL_TREE',
 'NoSuchPathError',
 'ODBError',
 'Object',
 'Optional',
 'ParseError',
 'PathLike',
 'PushInfo',
 'RefLog',
 'RefLogEntry',
 'Reference',
 'Remote',
 'RemoteProgress',
 'RemoteReference',
 'Repo',
 'RepositoryDirtyError',
 'RootModule',
 'RootUpdateProgress',
 'Sequence',
 'StageType',
 'Stats',
 'Submodule',
 'SymbolicReference',
 'TYPE_CHECKING',
 'Tag',
 'TagObject',
 'TagReference',
 'Tree',
 'TreeModifier',
 'Tuple',
 'Union',
 'UnmergedEntriesError',
 'UnsafeOptionError',
 'UnsafeProtocolError',
 'UnsupportedOperation',
 'UpdateProgress',
 'WorkTreeRepositoryUnsupported',
 'remove_password_if_present',
 'rmtree',
 'safe_decode',
 'to_hex_sha']

In [20]: len(git.__all__)
Out[20]: 75

In [21]: len(all)
Out[21]: 67
```

Could you also sort the list please? This makes it easier to maintain I think. Thank you.

**Comment by DeflateAwning** [comment]
I simply ran the existing code that was there, and then hard-coded it, removing entries that Pyright said were invalid.

Is this new list the complete list that should be used?

**Comment by Byron** [comment]
> [..] removing entries that Pyright said were invalid.

I think this explains the mismatch - I created this list based on what's actually there, without looking at a linter. My take on this is that it should be a complete substitution, and no entry can be missing, in order to remain compatible.

> Is this new list the complete list that should be used?

Yes, I think so. It would be interesting to know what Pyright is complaining about, but would hope that can be fixed without altering the contents of `__all__`.

Thanks for bearing with me on this one.

**Review by mobileaqsa — APPROVED** [review]

**Comment by DeflateAwning** [comment]
Implemented these changed, please merge :)

**Comment by DeflateAwning** [comment]
To fully fix the type hinting issues in all files I've modified here (https://github.com/gitpython-developers/gitdb/pull/98), merge this PR on gitdb, and bump the submodule version

**Comment by Byron** [comment]
It seems the NOQA part doesn't kick in for some reason - maybe this can also be validated locally by use of a `venv` or `tox`.

**Comment by DeflateAwning** [comment]
Should finally be good now! You'll probably want to squash and merge though, as I had a time stuggling with the linter (some new things were learned though)

**Comment by Byron** [comment]
Thanks a lot, it seems correct now.

For future reference, please prefer to rebase instead of merging. Unfortunately my tooling isn't quite up to the task to visualize complex commit graphs nicely (or I don't know how to use them).

**Comment by DeflateAwning** [comment]
I'll have to figure that out in GitHub Desktop

**Comment by DeflateAwning** [comment]
Can you do a release with these changes soon?

**Comment by Byron** [comment]
And here it is: https://github.com/gitpython-developers/GitPython/releases/tag/3.1.38 .

**Comment by DeflateAwning** [comment]
Thank you!

**Pull request merged**
