### PR TITLE
TST: test on travis while TMPDIR containing unicode chars

### PR DESCRIPTION
**Pull request by yarikoptic**
by popular [demand](https://github.com/gitpython-developers/GitPython/issues/506#issuecomment-255532637) ;)

### CODE REVIEW

**Comment by ankostis** [comment]
I managed to [fix PY3 TCs](https://travis-ci.org/ankostis/GitPython/builds/169899492) with f801a3aed7, but unfortunately, PY2 encodings for filepaths is a "casino"; surprisingly, Windows had [no problem!](https://ci.appveyor.com/project/ankostis/gitpython/build/1.0.352)

@@yarikoptic can you live by that alone?

**Comment by ankostis** [comment]
Both [*smmap*](https://travis-ci.org/ankostis/smmap/jobs/169913359) and [*gitdb*](https://travis-ci.org/ankostis/gitdb/builds/169913887) projects fails PY2 with a unicode tmp-dir :-(

**Comment by yarikoptic** [comment]
Dear @ankostis - if you are still interested in my opinion/desires -- I just want ideally both PY2 and PY3 supported.  ATM we do not *actively* support Windows (do Linux and OSX), so those platforms are of interest to me

**Comment by ankostis** [comment]
Of course!
Why do you say so?

**Comment by yarikoptic** [comment]
Saying just because you asked and I didn't reply ? In time so thought that may be you fixed it all and no feedback was needed any longer ;-)

**Comment by ankostis** [comment]
Anyhow, I've managed to fix PY3 on linux, please do try and fix the issue also in PY2; commence from f801a3a, as explained above.

**Comment by yarikoptic** [comment]
I ahead stashed my laptop away for a transatlantic flight to commence in few minutes... Will try when across the pond and finish driving 300 miles north  unless someone beats me to it ;-)

**Comment by Byron** [comment]
@yarikoptic I do hope you have landed safely :)! I would also be looking forward to your results whenever you have some time.

**Comment by yarikoptic** [comment]
thanks for the buzz @Byron ! Yes, I have landed successfully ;)  and today seems to be the day to respond to my own whinings on github (trying to fixup pandas as well atm).

Could you please clarify where that commit/branch you pointed to lives at since I can't find it on a quick look :-/

```shell
$> git log | grep surrogate
    fix(surrogateescape): enable on py2, fix tests
    fix(unicode): use surrogateescape in bytes.decode
changes on filesystem:                                                           
 git/ext/gitdb | 2 +-

$> git show f801a3aed7ab28b1c80fc1b573afb2b182eca995
fatal: bad object f801a3aed7ab28b1c80fc1b573afb2b182eca995

$> git show | head
commit b0c187229cea1eb3f395e7e71f636b97982205ed
Author: Sebastian Thiel <byronimo@gmail.com>
Date:   Thu Dec 8 16:07:11 2016 +0100

```
 
meanwhile I will merge current master, resolve conflict and push...

**Comment by Byron** [comment]
@yarikoptic Actually I don't know where said commit is, maybe @ankostis can help finding it. So far this issue seemed like a conversation between you to, I just wanted to reignite it after the transatlantic flight.

**Comment by ankostis** [comment]
I have f801a3a in my repo: https://github.com/ankostis/GitPython/commits/fix_py2_enc

**Comment by Byron** [comment]
Is there something we should do with this PR?

**Comment by ankostis** [comment]
I've managed to address the problem described only for python-3, as explained [in this comment](/gitpython-developers/GitPython/pull/543#issuecomment-256612502).

**Comment by Byron** [comment]
@ankostis Thanks again for your contribution, and sorry for the great delay (once again). It appears it is still having trouble [to deal with this](https://travis-ci.org/gitpython-developers/GitPython/jobs/182344771#L709) :/.

**Comment by yarikoptic** [comment]
pushed with current master merged in -- may be some things are already better ;-)

**Comment by Byron** [comment]
@yarikoptic This one will probably have to wait for another release. The current one should already make things better though :).

**Comment by yarikoptic** [comment]
sure!  I will merge current improved master again to see where we stand though
Cheers

**Pull request closed without merging**
