### PR TITLE
Don't suppress messages when logging is not configured

### LINKED ISSUE #1806: NullHandler added to all but git.repo.base logger
*This issue should not be confused with what the change in #1807 is trying to improve. The outcome of that PR is unrelated to this issue, because GitPython itself uses `logging.NullHandler` not `git.util.NullHandler`.*

Although the [recommended default](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) behavior for libraries is to allow messages of `WARNING` or higher severity to be displayed when the calling code does not configure logging, a library also has the option of causing its messages to be suppressed by default by registering an instance of `NullHandler` as a handler. (Logging is still happening; messages can still be subscribed to by the addition of other handlers.) GitPython takes this approach, though in a bit of a different way the Python documentation suggests for it. In GitPython, `NullHandler`s are registered for the individual modules' loggers rather than for a library-wide "top-level" logger.

This is with one exception. `git.repo.base` does not register a `NullHandler`:

```text
(.venv) ek@Glub:~/repos-wsl/GitPython (main $=)$ git grep -Fn NullHandler -- git/
git/cmd.py:85:log.addHandler(logging.NullHandler())
git/config.py:65:log.addHandler(logging.NullHandler())
git/objects/commit.py:56:log.addHandler(logging.NullHandler())
git/objects/submodule/base.py:60:log.addHandler(logging.NullHandler())
git/objects/submodule/root.py:26:log.addHandler(logging.NullHandler())
git/remote.py:69:log.addHandler(logging.NullHandler())
git/util.py:1297:class NullHandler(logging.Handler):
(.venv) ek@Glub:~/repos-wsl/GitPython (main $=)$ git grep -Fn logging.getLogger -- git/
git/cmd.py:84:log = logging.getLogger(__name__)
git/config.py:64:log = logging.getLogger("git.config")
git/objects/commit.py:55:log = logging.getLogger("git.objects.commit")
git/objects/submodule/base.py:59:log = logging.getLogger("git.objects.submodule.base")
git/objects/submodule/root.py:25:log = logging.getLogger("git.objects.submodule.root")
git/remote.py:68:log = logging.getLogger("git.remote")
git/repo/base.py:92:log = logging.getLogger(__name__)
git/util.py:107:log = logging.getLogger(__name__)
```

It is unclear if this is intentional. It is easy to miss one (see #666) so it may well be an unintended omission.

I believe one of the following changes should be made, but I do not know which:

- State in a comment (or docstring) in `git.repo.base` why its logger is special.
- Register a `NullHandler` for the `git.repo.base` logger.
- Stop registering `NullHandler`s for the other loggers.

I am not sure if causing messages from GitPython, even of `WARNING` and higher severity, not to appear by default is actually considered desirable. The `NullHandler`s were introduced in #300. At that time, this was not with the goal of suppressing messages, but instead to avoid "No handlers could be found for logger" errors. It is no longer necessary to do that [since Python 3.2](https://docs.python.org/3/howto/logging.html#what-happens-if-no-configuration-is-provided). So if the only reason is as given in #300 and suppressing messages is not itself a goal, then the `NullHandler`s should be removed, unless it is considered important to keep them for compatibility with previous expected behavior of GitPython.

Other than the first approach of adding a comment, any changes could be inconvenient to developers of programs or other libraries that use GitPython, and to users of such software. I am unsure if they could reasonably be considered breaking. I am inclined to think that most such changes would be non-breaking but still should not be undertaken without carefully considering the impact on users and developers who may expect the current behavior.

### PR DESCRIPTION
**Pull request by EliahKagan**
Fixes #1806

This stops adding `NullHandler` instances to GitPython's loggers. As noted in #1806, when they were added in #300 this prevented errors when GitPython logged messages and logging was not enabled, but since Python 3.2 there is a logger of last resort providing a nicer default behavior of showing the messages. (They are still shown with better formatting if logging is configured, even if just done with `logging.basicConfig()`, so applications should still typically configure logging.)

This also makes a few more minor related changes, detailed in the commit messages. This includes changing variable names from `log` to `_logger`, as mentioned in https://github.com/gitpython-developers/GitPython/issues/1806#issuecomment-1907690901, as well as consistently passing `__name__` to `logging.getLogger` instead of hard-coding names in a few places, as mentioned in https://github.com/gitpython-developers/GitPython/issues/1808#issuecomment-1911301659.

The major effect of the changes here is that messages of level `WARNING` or higher are not suppressed by default anymore, even when logging is not configured. So I could have included a change here to take care of #1808 as well, such as dc62096. But I plan to introduce that in a future pull request instead, because it would be best to add tests for it, which I think should build on the tests proposed in #1812. If both #1812 and this PR are merged, I can add tests followed by the changes from dc62096 that would make them pass. (If they are not merged, or they are merged with major changes, then that will also clarify how to move forward with making a warning from the initial refresh use the logging framework.)

This shows as resolving several CodeQL alerts and also adding new alerts that correspond exactly to them. This happens as a result of renaming `log` to `_logger`; CodeQL considers the alert resolved because there are no more calls to `log`, and issues new equivalent alerts for the same situations with `_logger`. The new alerts produce a failing *Code scanning results* check for the PR.

### CODE REVIEW

**Review by Byron — APPROVED** [review]
Thanks a lot for your help!

Once CI is green I will merge this PR and hope this can pave the way to improve the `git.refresh()` messaging as well :).

**Comment by Byron** [comment]
It looks like pypi packages fail to refresh in the cygwin job for some reason, the last one timed out after 6h.

Merging anyway.

**Comment by EliahKagan** [comment]
Sorry about leaving this in the draft state without explanation. I had hoped to check if the CodeQL results would cause a "Code scanning results" failure in the merge commit, as well as to improve on, or if not then to describe, the new Cygwin failure where `pip` blocks indefinitely while downloading some packages. But the problem in the Cygwin run appears separate from the changes in this PR. At some point in time between #1812 and this PR, something changed so that `pip` never finishes downloading `wheel`. If the workflow is edited to make it not download `wheel`, then it never finishes downloading `codecov`. Fortunately, my having left it this way [did not prevent](https://github.com/gitpython-developers/GitPython/pull/1813#event-11611071649) you from merging it.

It looks like the current situation on this repository's main branch is difficult to evaluate because many more CI checks on the pushed merge commit have been cancelled than are affected by either of these issues. Would you be willing to rerun the CI workflows on 10cdd03 *other* than the Cygwin one?

**Comment by Byron** [comment]
Apologies for the premature merge, indeed I considered all failures unrelated and decided to just ignore them, particularly after having seen 6h timeouts for Cygwin. After restarting CI on the 10cdd03 , [Cygwin still hangs](https://github.com/gitpython-developers/GitPython/actions/runs/7671078305/job/20915661161). Does that mean that Cygwin based workflows don't work for anyone right now? That would be major breakage and I have no idea how it can stall forever.

**Comment by EliahKagan** [comment]
Thanks for rerunning the checks on 10cdd03. I see everything other than the Cygwin job is okay. (I suspected this, since it is the situation in my fork since fast-forwarding, but I wasn't sure if there was more going on related to their cancellation.)

> Apologies for the premature merge, indeed I considered all failures unrelated and decided to just ignore them

The merge seems fine to me--no need to apologize. The CodeQL failure was due to the changes here, though the new alerts were replacing equivalent previous alerts. But I think you're mainly talking about the Cygwin failure, which is not from the changes here. It happens even when rerunning the Cygwin test job on a commit where it has successfully completed before.

> Does that mean that Cygwin based workflows don't work for anyone right now?

They're probably not broken for everyone, because the problem seems only to happen with `pip`, and only when attempting to download *some* packages from PyPI but not others. I am also unable to reproduce it locally. But it may be that such use is broken for everyone, or that Cygwin-based jobs are otherwise degraded for everyone. Or there could be a subtle bug in the `test-cygwin.yml` workflow that combines with an external change to produce the problem, as in #1784.

> That would be major breakage and I have no idea how it can stall forever.

Even though `pip` has a default socket timeout of 15 seconds as documented in the output `pip --help` for the `--timeout` option, I wonder if some network operation is still stalling, which seems to happen on Windows sometimes (#525, #530, 8364597, https://github.com/gitpython-developers/GitPython/issues/1676#issuecomment-1735052752). Even though it doesn't happen when the native Windows jobs run `pip`, I still wonder if that is involved. Strange low-level-ish network for downloading specific files is unusual but has been known to happen on CI (https://github.com/actions/runner-images/discussions/8791).

My guess is that it's something else, though. I'll look into it further.

**Comment by EliahKagan** [comment]
I've learned enough about the Cygwin problem to find what I believe to be a reasonable workaround, which I've proposed in #1814 along with my findings.

**Pull request merged**
