### PR TITLE
ENH: skip test_is_ancestor on git versions < 1.8.0 not supporting git merge-base --is-ancestor

### PR DESCRIPTION
**Pull request by yarikoptic**
as I have whined somewhere sometime ;)

### CODE REVIEW

**Comment by Byron** [comment]
Thanks ! 
I believe a decorator is missing before it can work.

**Comment by yarikoptic** [comment]
god bless tests and travis! ;) force pushed updated one, hopefully this one would be correct ;)

**Comment by yarikoptic** [comment]
d'oh -- forgot to ping you @Byron -- issues were addressed, could it be merged? ;)

**Comment by Byron** [comment]
Thanks ! The lack of notifications turns out to be a true footgun.

**Pull request merged**
