### PR TITLE
Update Remotes section

### PR DESCRIPTION
**Pull request by forresthopkinsa**
The Remotes section was missing some pretty important info

### CODE REVIEW

**Comment by Byron** [comment]
Thanks a bunch!
Good to have runnable documentation:).

**Comment by forresthopkinsa** [comment]
No problem, I spent like a week trying to figure this out and I thought I'd
make it easier for anyone else haha

**Comment by forresthopkinsa** [comment]
Hey @Byron , I'm new to ReadTheDocs, so I am wondering whether its cache hasn't updated yet or if I did something wrong there? Thanks!

**Comment by Byron** [comment]
@forresthopkinsa It looks like the 'latest' documentation is not shown, but only 'stable', which appears to be the most recent tag. With the next release, your change will become visible automatically.

**Comment by forresthopkinsa** [comment]
Oh, I see. Thanks!

**Pull request merged**
