### PR TITLE
Retrofit `repo` class as context-man to cleanup global mman on repo-delete

### PR DESCRIPTION
**Pull request by ankostis**
Some changes for this release:
See #553 for difficulties when working on Windows, where open file-handles actually "lock" the underlying files, and repos cannot be deleted.

More changes:

- Small pythonism on  #541, improves  docstring of `cmd._call_process()`.
- Export `gitpython.util.rmtree()` for deleting repos in *Windows* where blobs are readonly.

### CODE REVIEW

**Comment by Byron** [comment]
@ankostis Do you think I should wait till tomorrow until I cut the release to be able to include this one? Or would you prefer to just have this released separately at a later time?

**Comment by Byron** [comment]
@nvie I just created a new release.
@ankostis I will follow this PR and make a release when needed. Thanks to the `Makefile`, that became easy and convenient (interestingly, I wasn't aware it existed anymore :)).

**Comment by ankostis** [comment]
Sorry @Byron , I've just seen your message. 

I'm not exactly sure what happened and you could not include my PR in 2.1.1. 
I believe it ready to be merged.
is this  right, or this PR relies on features from a different GitDB/smmap?

**Comment by Byron** [comment]
Even though the implementation seems to be in place, it would certainly be nice to include an example in the `test_docs.py` to show people how to use it. I for one wouldn't know myself actually, just because my experience with context managers is very limited.
Do you think you could add an example? I could then include it in the tutorial and write some prose around it :).

**Comment by ankostis** [comment]
Apologies for not having the time,
but I really believe this little PR wroth to have it.

Too overloaded to fix the TCs in the next weeks :-(

**Comment by Byron** [comment]
I think so too :)! Sorry for the incredible delays.

**Pull request merged**
