### PR TITLE
Replace GIT_SSH with GIT_SSH_COMMAND for SSH key management.

### PR DESCRIPTION
**Pull request by teeberg**
Also move untestable documentation out of test.

Related: #234, #242

### CODE REVIEW

**Comment by teeberg** [comment]
I actually think it's a really cool idea to test the documentation like this, but if you have to say that we don't actually make the call because the test setup won't allow us to, I'd rather remove it from the test... :-)

**Comment by Byron** [comment]
Thank you ! I wouldn't mind putting in the example in clear-text in this case. 
However, as GitPython aims to support multiple different versions of the git commandline program, it would be great to keep both versions, stating which `git --version` you require to make use of either one.
Do you think you can make this change for me so I can make the merge ?
Thanks in advance

**Comment by Byron** [comment]
I'd like to make a new release this week, and would be glad if I could merge this PR. Can you have a look at my previous request ? It shouldn't take long. If you have no time for this just let me know and I will do it for you.
Thanks

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/Q-sl62-MWAE).

**Comment by teeberg** [comment]
Thanks for taking over. :-) I was willing to do it, but I'm indeed rather busy and it probably takes you way less time.

**Pull request merged**
