### PR TITLE
Issue 1261

### LINKED ISSUE #1261: repo.tag() only accepts 'ref/tags/tagname' instead of just 'tagname'
The param comment for `tag()` in `base.py` mentions `0.1.5` and `tags/0.1.5` as valid inputs, however the call to `TagReference` calls the inherited constructor (`Reference` in reference.py) with the default `check_path=True`, which returns a `ValueError`, if the tag/path given doesnt start with `self._common_path_default + '/'`.

Either the param comment needs to be adjusted or the tag parameter cleaned up so that it only returns the tag value to `Reference.__init__`.

pycharm64_UlSdzGazov
pycharm64_nnw8DMULi2

### PR DESCRIPTION
**Pull request by bytefluxio**
Fixes #1261

### CODE REVIEW

**Comment by bytefluxio** [comment]
I initially wanted to add [parameterized](https://github.com/wolever/parameterized), but there was an issue somewhere, which is why I decided to just collect the errors

**Comment by Byron** [comment]
Thanks a lot!

With `tox -e type` you should be able to pacify the type checker. It looks like it's not sure `startswith` actually is  available.

**Comment by bytefluxio** [comment]
I come from a strongly typed language, so this caught me unawares.

since reference.py doesn't do a PathLike check, I removed mine, too.

reference.py:
```
    def __init__(self, repo, path, check_path=True):
        """Initialize this instance
        :param repo: Our parent repository

        :param path:
            Path relative to the .git/ directory pointing to the ref in question, i.e.
            refs/heads/master
        :param check_path: if False, you can provide any path. Otherwise the path must start with the
            default path prefix of this type."""
        if check_path and not path.startswith(self._common_path_default + '/'):
            raise ValueError("Cannot instantiate %r from path %s" % (self.__class__.__name__, path))
        super(Reference, self).__init__(repo, path)
```

**Comment by bytefluxio** [comment]
Weird, that my tests ran through without issues on Python 3.9.5 ¯\_(ツ)_/¯

Didn't use tux though, since I'm new to python, I had no idea about it.

**Comment by Byron** [comment]
> I come from a strongly typed language, so this caught me unawares.

I stopped trying to understand or follow or write python many years ago, too, and I am blissfully unaware of how the typing really works. Removing types is quite alright here I think and more knowledgable individuals can add them later if they see benefits.

Anyway, with a tiny adjustment it worked as expected. Thanks a lot for your contribution - thanks to you GitPython finally does as it says on the packaging (in this instance) 10 years or so later 😅.

**Comment by bytefluxio** [comment]
Thanks for the test fix.

I fixed that with "Fixes test to not throw false negative results" 057514e85bc99754e08d45385bf316920963adf9

But threw it away when I "Reverts auto format introduced with 2dbc2be" 79e24f78fa35136216130a10d163c91f9a6d4970

Shame on me

**Pull request merged**
