### PR TITLE
Adding support for git remote set-url/get-url API to Remote

### PR DESCRIPTION
**Pull request by guyzmo**
Both commands enable handling of a little known feature
of git, which is to support multiple URL for one remote.
You can add multiple url using the `set_url` subcommand of
`git remote`. Though listing them is also handy, so there's
a nice method to do it, using the configuration.

### CODE REVIEW

**Comment by guyzmo** [comment]
might need to write some tests for those?

**Comment by Byron** [comment]
Oh yes please ! It should be relatively straightforward to deduce how to write tests for this by looking at the existing ones. Usually there are helper functions to setup even more complex fixtures.

**Comment by Byron** [comment]
Oh, before I forget, could you also look at how existing methods are documented and match the documentation style ? This would include documenting all parameters, for example.

**Comment by guyzmo** [comment]
I might, but sadly I'm now in the train, going away for four days, during which I'm on a crappy tablet on which I cannot work. Though, I very much would like to see this new methods included in the next patchset so I can remove the monkey patching from my own codebase as well :-)

cf https://github.com/guyzmo/git-repo/blob/master/git_repo/services/service.py#L25-43

**Comment by guyzmo** [comment]
I've been trying to write tests for those, but I'm having issue making it right…

Would you be available in any chat so we could discuss this slightly more efficiently, and avoid "chatting" over issues comments?

**Comment by guyzmo** [comment]
So, I've squashed my commit with a new one, featuring a few changes:

* The `set_url` method is a direct wrapper for `git remote set-url` ;
* the `urls` property is providing an iterator over the remote's URLs (I followed how you named `refs`)

Then I've added a couple of convenience methods, to avoid adding awkward arguments to control `set_url`:

* the `add_url` method is there so you can add an URL to a remote
* and `delete_url` method is to delete one.

Finally, I've added a test covering all the new code, with a couple of edge cases, and wrote pydoc for those functions. I hope it's how you like it, mates!

**Comment by guyzmo** [comment]
I rolled back the `urls` property, because that was failing on Travis, which isn't using latest git.

The `git remote get-url` API has been introduced in [`git 2.7.0`](https://git-scm.com/docs/git-remote/2.7.0), and wasn't available [before](https://git-scm.com/docs/git-remote/2.6.3).

**Comment by guyzmo** [comment]
can you ping me when you think you'll be able to merge, and publish on pypi¸ and what version that will be? So I can update my setup.py accordingly ☺

**Comment by Byron** [comment]
If @nvie doesn't beat me to it, I will get the new release on the way on my next maintenance slot. Maybe tomorrow ... .

**Comment by guyzmo** [comment]
thank you ;-)

preparing my own code to be ready to point to the right version! :-)

**Comment by nvie** [comment]
I'll add 2 more bug fixes tonight to this release. After I'm done with those, I'll roll a new release :)

**Pull request merged**
