### PR TITLE
Add support to pass clone options that can be repeated multiple times

### PR DESCRIPTION
**Pull request by ninloot**
This PR addresses issue #824, allowing options to be passed directly without additional processing by the underlying framework.

### CODE REVIEW

**Comment by ninloot** [comment]
It appears that the tests that are failing were failing prior to my change so I don't think my change is a regression.

**Comment by Byron** [comment]
Thanks a lot for your contribution! It's very much appreciated :)!

**Comment by Byron** [comment]
I am closing this PR as due to me apparently making a mistake while merging things locally, Github is unable to see the branch has actually been merged. Your commit is here 41b9cea832ad5614df94c314d29d4b044aadce88

**Comment by ninloot** [comment]
Thanks for accepting the change.
 - Steve -

**Pull request closed without merging**
